// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA__gu8sMYYQKGhQ4e7S_nFjYktTE_SSm4',
    appId: '1:781013558976:web:149864f6a26db1f4e1af25',
    messagingSenderId: '781013558976',
    projectId: 'progym-fb114',
    authDomain: 'progym-fb114.firebaseapp.com',
    databaseURL: 'https://progym-fb114-default-rtdb.firebaseio.com',
    storageBucket: 'progym-fb114.appspot.com',
    measurementId: 'G-M06LQJB54T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCta7SgJ9QD06hhdsjLBVJpkF3_EGTlaqc',
    appId: '1:781013558976:android:cc3bb97f7f26ca77e1af25',
    messagingSenderId: '781013558976',
    projectId: 'progym-fb114',
    databaseURL: 'https://progym-fb114-default-rtdb.firebaseio.com',
    storageBucket: 'progym-fb114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-L57d9hXJvB7TZnCmn1XnHaVmAqtd2Q',
    appId: '1:781013558976:ios:5568ef7fa3f5a6e7e1af25',
    messagingSenderId: '781013558976',
    projectId: 'progym-fb114',
    databaseURL: 'https://progym-fb114-default-rtdb.firebaseio.com',
    storageBucket: 'progym-fb114.appspot.com',
    iosBundleId: 'com.example.proGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY-L57d9hXJvB7TZnCmn1XnHaVmAqtd2Q',
    appId: '1:781013558976:ios:cac34792ae193e27e1af25',
    messagingSenderId: '781013558976',
    projectId: 'progym-fb114',
    databaseURL: 'https://progym-fb114-default-rtdb.firebaseio.com',
    storageBucket: 'progym-fb114.appspot.com',
    iosBundleId: 'com.example.proGym.RunnerTests',
  );
}
